version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: realja.me
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - 1000:80
      - 1001:443
    restart: unless-stopped
